### ISSUE TITLE
Bug: No longer works on Mac OS < 10.15 from 4.9 onwards: Symbol not found: ____chkstk_darwin

### ISSUE THREAD

**Issue by daviewales** [obsproject/obs-websocket#937]
### Operating System Info

macOS 10.13

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.4

### obs-websocket Version

4.9.1

### OBS Studio Log URL

The program crashes before writing the details to the log.  Log from Terminal included below.

### OBS Studio Crash Log URL

The program crashes before writing the details to the log.  Log from Terminal included below.

### Expected Behavior

OBS should launch. Note that obs-websocket 4.8 _does_ work.

### Current Behavior

OBS crashed on launch after installing obs-websocket with the following error on the terminal:

```
info: [obs-websocket] WSServer::start: Not locked to IPv4 bindings
info: [obs-websocket] server started successfully on port 4444
info: [obs-websocket] IO thread started.
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Library/Application Support/obs-studio/plugins/obs-websocket/bin/obs-websocket.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Library/Application Support/obs-studio/plugins/obs-websocket/bin/obs-websocket.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

### Steps to Reproduce

1. Install obs-websocket
2. Launch OBS

### Anything else we should know?

Full log below:

```
❯ ./obs
info: Using preferred locale 'en-GB'
info: Rosetta translation used: false
info: CPU Name: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
info: CPU Speed: 2200MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 16384MB Total
info: OS Name: Mac OS X
info: OS Version: Version 10.13.6 (Build 17G6030)
info: Kernel Version: 17.7.0
info: hotkeys-cocoa: Using layout 'com.apple.keylayout.Australian'
info: Current Date/Time: 2022-04-29, 22:49:35
info: Browser Hardware Acceleration: true
info: Qt Version: 5.15.2 (runtime), 5.15.2 (compiled)
info: Portable mode: false
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 27.2.4 (mac)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter Intel Inc. Intel Iris Pro OpenGL Engine
info: OpenGL loaded successfully, version 4.1 INTEL-10.36.23, shading language 4.10
info: ---------------------------------
info: video settings reset:
	base resolution:   1440x900
	output resolution: 1440x900
	downscale filter:  Bicubic
	fps:               60/1
	format:            NV12
	YUV mode:          709/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: Failed to load 'en-GB' text for module: 'aja-output-ui.so'
warning: No AJA devices found, skipping loading AJA UI plugin
warning: Failed to initialize module 'aja-output-ui.so'
warning: Failed to load 'en-GB' text for module: 'aja.so'
warning: No AJA devices found, skipping loading AJA plugin
warning: Failed to initialize module 'aja.so'
warning: Failed to load 'en-GB' text for module: 'coreaudio-encoder.so'
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
warning: Failed to load 'en-GB' text for module: 'frontend-tools.so'
error: os_dlopen(libpython3.9.dylib->libpython3.9.dylib): dlopen(libpython3.9.dylib, 257): image not found

warning: [Python] Could not load library: libpython3.9.dylib
warning: Failed to load 'en-GB' text for module: 'mac-capture.so'
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
warning: Failed to load 'en-GB' text for module: 'mac-virtualcam.so'
warning: Failed to load 'en-GB' text for module: 'mac-vth264.so'
info: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
info: [obs-browser]: Version 2.17.13
info: [obs-browser]: CEF Version 95.0.0-MediaHandler.2462+g95e19b8+chromium-95.0.4638.69
info: [obs-browser]: OS version older than 10.15 Disabling hwaccel
warning: Failed to load 'en-GB' text for module: 'obs-vst.so'
warning: Failed to load 'en-GB' text for module: 'obs-x264.so'
warning: Failed to load 'en-GB' text for module: 'rtmp-services.so'
info: [vlc-video]: VLC 3.0.17.3 Vetinari found, VLC video source enabled
warning: Failed to load 'en-GB' text for module: 'obs-websocket.so'
info: [obs-websocket] you can haz websockets (version 4.9.1)
info: [obs-websocket] qt version (compile-time): 5.15.2 ; qt version (run-time): 5.15.2
info: [obs-websocket] module loaded!
info: ---------------------------------
info:   Loaded Modules:
info:     obs-websocket.so
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-vst.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     mac-vth264.so
info:     mac-virtualcam.so
info:     mac-syphon.so
info:     mac-decklink.so
info:     mac-capture.so
info:     mac-avcapture.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-ouput-ui.so
info:     decklink-captions.so
info:     coreaudio-encoder.so
info: ---------------------------------
info: ==== Startup complete ===============================================
info: Switched to Preview/Program mode
info: ------------------------------------------------
info: All scene data cleared
info: ------------------------------------------------
info: coreaudio: device 'Built-in Microphone' initialized
info: [Loaded global audio device]: 'Mic/Aux'
info: Video Capture Device: Selected device 'FaceTime HD Camera'
info: Video Capture Device: Using preset 1280x720
info: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux)

info: Video Capture Device 2: Selected device 'FaceTime HD Camera'
info: Video Capture Device 2: Using preset 1280x720
[swscaler @ 0x7fd5a4881600] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fd5a48b4600] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fd5a28d1c00] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fd5a30e4200] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fd5a30e4200] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0x7fd5a28ea000] deprecated pixel format used, make sure you did set range correctly
info: Switched to scene 'Scene 3'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene':
info:     - source: 'Scene 2' (scene)
info:     - source: 'Video Capture Device' (av_capture_input)
info: - scene 'Scene 2':
info:     - source: 'Video Capture Device 2' (av_capture_input)
info:     - source: 'Text (FreeType 2)' (text_ft2_source)
info: - scene 'Scene 3':
info:     - source: 'Image Slide Show' (slideshow)
info:     - source: 'RTMP Stream' (vlc_source)
info: - scene 'Scene 4':
info: ------------------------------------------------
info: [obs-websocket] WSServer::start: Not locked to IPv4 bindings
info: [obs-websocket] server started successfully on port 4444
info: [obs-websocket] IO thread started.
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Library/Application Support/obs-studio/plugins/obs-websocket/bin/obs-websocket.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Library/Application Support/obs-studio/plugins/obs-websocket/bin/obs-websocket.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by greebowarrior** [comment]
'm having a similar issue on macOS 11.6.6 with OBS 27.4.2 and WS 4.9.1.
OBS is crashing in startup, and the logs end straight after the WSServer::start line

**Comment by tt2468** [comment]
> I'm having a similar issue on macOS 11.6.6 with OBS 27.4.2 and WS 4.9.1. OBS is crashing in startup, and the logs end straight after the `WSServer::start` line. I've tried using 4.9.1, 4.9.1-compat, and the 5.0.0-beta, but the outcome is always the same. Removing the plug-in solves the issue.

You appear to be having an unrelated issue. Please come to the Discord if you are still having issues, and we can help you look into it further.

**Comment by tt2468** [comment]
Sorry, but 4.x versions are no longer supported. Yes this is an issue, but unfortunately we have no plans of providing any fixes. 10.13 is quite old at this point.

**Comment by greebowarrior** [comment]
> I'm having a similar issue on macOS 11.6.6 with OBS 27.4.2 and WS 4.9.1.
> OBS is crashing in startup, and the logs end straight after the `WSServer::start` line.
> I've tried using 4.9.1, 4.9.1-compat, and the 5.0.0-beta, but the outcome is always the same.
> Removing the plug-in solves the issue.

Update: seems this issue may have been caused by the Teleport plug-in. I had v0.4.1 installed, will test with the latest 0.5.0 release soon

Current hypothesis is its something to do with Teleport appearing as an active streaming session, which I discovered when opening the WS config dialog.
