### ISSUE TITLE
Bug: Build fails: error: type alias redefinition with different types ('OBSRef<obs_source_t *, ___source_dummy_addref, obs_source_release>'

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-websocket#954]
### Operating System Info

Other

### Other OS

FreeBSD

### OBS Studio Version

27.2.4

### obs-websocket Version

4.9.1

### OBS Studio Log URL

n/a

### Expected Behavior

successful build

### Current Behavior

```
In file included from /disk-samsung/freebsd-ports/multimedia/obs-websocket/work/obs-websocket-4.9.1/src/WSRequestHandler.cpp:27:
In file included from /disk-samsung/freebsd-ports/multimedia/obs-websocket/work/obs-websocket-4.9.1/src/WSRequestHandler.h:31:
In file included from /disk-samsung/freebsd-ports/multimedia/obs-websocket/work/obs-websocket-4.9.1/src/rpc/RpcRequest.h:23:
/disk-samsung/freebsd-ports/multimedia/obs-websocket/work/obs-websocket-4.9.1/src/rpc/../obs-websocket.h:30:7: error: type alias redefinition with different types ('OBSRef<obs_source_t *, ___source_dummy_addref, obs_source_release>' (aka 'OBSRef<obs_source *, ___source_dummy_addref, obs_source_release>') vs 'OBSRefAutoRelease<obs_source_t *, obs_source_release>' (aka 'OBSRefAutoRelease<obs_source *, obs_source_release>'))
using OBSSourceAutoRelease =
      ^
/usr/local/include/obs/obs.hpp:62:7: note: previous definition is here
using OBSSourceAutoRelease =
      ^
In file included from /disk-samsung/freebsd-ports/multimedia/obs-websocket/work/obs-websocket-4.9.1/src/WSRequestHandler.cpp:27:
In file included from /disk-samsung/freebsd-ports/multimedia/obs-websocket/work/obs-websocket-4.9.1/src/WSRequestHandler.h:31:
In file included from /disk-samsung/freebsd-ports/multimedia/obs-websocket/work/obs-websocket-4.9.1/src/rpc/RpcRequest.h:23:
/disk-samsung/freebsd-ports/multimedia/obs-websocket/work/obs-websocket-4.9.1/src/rpc/../obs-websocket.h:32:7: error: type alias redefinition with different types ('OBSRef<obs_sceneitem_t *, ___sceneitem_dummy_addref, obs_sceneitem_release>' (aka 'OBSRef<obs_scene_item *, ___sceneitem_dummy_addref, obs_sceneitem_release>') vs 'OBSRefAutoRelease<obs_sceneitem_t *, obs_sceneitem_release>' (aka 'OBSRefAutoRelease<obs_scene_item *, obs_sceneitem_release>'))
using OBSSceneItemAutoRelease =
      ^
/usr/local/include/obs/obs.hpp:65:7: note: previous definition is here
using OBSSceneItemAutoRelease =
      ^
```

### Steps to Reproduce

normal build with clang-13 on FreeBSD 13.1

**Comment by tt2468** [comment]
You must build all 4.x branches against OBS 27.1.3.

**Comment by yurivict** [comment]
@tt2468 5.0.1 still breaks the same way with obs-studio-27.2.4

**Comment by tt2468** [comment]
5.0.1 does not define OBSSceneItemAutoRelease, so I don't see how that is possible.

**Comment by yurivict** [comment]
Sorry, my bad. I confused the version when I was trying.
